config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :static_pages, only: [:index]

  root "static_pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    flickr_api_key = Figaro.env.flickr_api_key
    flickr_shared_secret = Figaro.env.flickr_shared_secret
    flickr = Flickr.new(flickr_api_key, flickr_shared_secret)

    begin
      if params[:commit] == "Submit"
        user_id = flickr_params
        @user_photos = flickr.photos.search(user_id: user_id, format: 'json')
      end
    rescue Flickr::FailedResponse
      flash[:alert] = "ID is invalid"
      @user_photos = []
    end
  end

  private

  def flickr_params
    params.permit(:id)[:id] || ""
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlickrApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div class="d-flex justify-content-center">
        <div class="alert alert-info d-inline-flex">
          <%= msg %>
        </div>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<div class="container">
  <h1>FLICKR PHOTO STREAM</h1>
  <%= form_with url: static_pages_path, method: 'get' do |form| %>
    <%= form.label(:id, 'Flickr User ID') %>
    <%= form.text_field(:id)%>
    <%= form.submit 'Submit'%>
  <% end %>
</div>

<div>
  <% if !@user_photos.nil? %>
    <% @user_photos.each_with_index do |photo, idx| %>
      <%= image_tag("https://live.staticflickr.com/#{photo.server}/#{photo.id}_#{photo.secret}.jpg", height: 400)%>
    <% end %>
  <% end %>
</div>